### PR TITLE
Add macOS 10.11-10.13 support

### PR DESCRIPTION
**Pull request by zmwangx**
Another year, another Darwin version.

### CODE REVIEW

**Comment by zmwangx** [comment]
Updated for macOS 10.13.

**Comment by ilovezfs** [comment]
:tada: Thanks @zmwangx and @moretension!

**Comment by jorvi** [comment]
@zmwangx since duti is pretty ill-maintained: I'm working on a fork [here](https://github.com/jorvi/utid) that basically pulls the best bits from all the forks on the network. I use duti myself, so I'm happy to maintain it (and give others push rights if wanted/needed). One giant advantage: it doesn't use autoconf so no need for constant macOS version support updates. But back to my main point: it seems to me that its much to all just bundle our powers :)

**Comment by jaruba** [comment]
@jorvi

You should publish your fork as it's own repo and give all the necessary credit that led you to that point in the `Readme.md`. The reason I'm suggesting this is because forks don't have a Issues tab, which is needed if you want to maintain something.

Also, in your readme file, in the Support section, it writes:

> You can submit bug reports and feature requests for this version of the software at the utid GitHub project page:
> `https://github.com/jovi/utid/`

That url leads to a 404 page, and if you meant to write `jorvi` instead of `jovi` in the url, then the text is misleading, because that leads to a fork where you cannot submit bug reports or feature requests.

**Comment by jaruba** [comment]
@moretension it would be great if you could please try to find the time to build the project and add a new release that includes this PR as the last Duti release is from december 2014 and doesn't support a lot of OSX versions already

**Comment by ilovezfs** [comment]
@jaruba sorry. I thought this was the Homebrew/homebrew-core repository. In any case, the patch from this PR was applied to the Homebrew formula already if you `brew install duti`.

**Comment by jaruba** [comment]
@ilovezfs i'm glad Homebrew updated it, but that doesn't solve the issue of people finding this project on github, going to releases, finding out that the last release is from 2014, downloading it and realising it doesn't work for the last 3 big OSX versions although the code has been updated to work with them. But you're right, I should make a separate issue report instead of commenting on a PR.

**Comment by zmwangx** [comment]
> forks don't have a Issues tab

That's false. It's just disabled by default, and can be enabled with a click in settings.

**Pull request merged**
