### PR TITLE
add OS X 10.11 El Capitan support

### PR DESCRIPTION
**Pull request by zmwangx**
This patch (analogous to https://github.com/moretension/duti/commit/594dfe0c9d4693afe4dbc23c505764292a48c6b4) would fix https://github.com/moretension/duti/issues/12.

### CODE REVIEW

**Comment by zmwangx** [comment]
Ah, I didn't see #11, sorry. Anyway, this patch is better since it doesn't hard-code the SDK path.

**Comment by neochief** [comment]
Works for me.

**Comment by mhenrixon** [comment]
:+1:

**Comment by Phrohdoh** [comment]
Works for me. 👍

**Comment by zmwangx** [comment]
Closing in favor of #20.

**Pull request closed without merging**
